spring.application.name=backEnd

# application.properties에 작성
# 서버 포트 번호
server.port=8090

# 소스파일에 변화가 있을 때 자동으로 서버 재 시작 설정
spring.devtools.restart.enabled=true

# DB 접속 주소 (xe 대신 본인의 Service Name 입력)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
# 오라클 드라이버 클래스
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# 계정 정보
spring.datasource.username=java
spring.datasource.password=java

# mapper 경로
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

